### ISSUE TITLE
Documentation for CalculIX adapter debian packages missing

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#108]
We now have Debian packages for the CalculiX adapter: https://github.com/precice/calculix-adapter/pull/72

We should also add the respective documentation, once we have the first release with packages.

**Comment by MakisH** [comment]
@boris-martin do you think you could add 1-2 lines for this in the "Get the adapter" page? Still noting that this is experimental, maybe.

**Comment by boris-martin** [comment]
@MakisH Ideally I'd do that once I can put a link to the release tag, so that the user doesn't need to look into the Actions artifacts
