### ISSUE TITLE
Raw URLs are not clickable

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice.github.io#116]
Usually raw URLs in markdown are rendered as clickable. For example https://precice.org/ (Markdown: `https://precice.org/`). Our website does not follow this rule. This requires work-arounds like [https://precice.org/](https://precice.org/) (Markdown: `[https://precice.org/](https://precice.org/)`).

From my perspective this is absolutely not critical, because a work-around exists. But it is still a bug, because we do not follow the normal behavior of markdown here.

**Comment by chlorenz** [comment]
As far as I know URLs are not being rendered according to the original Markdown specification, but pretty much all popular Markdown parsers do it. In particular Github Flavoured Markdown (GFM).

We are using kramdown as a renderer which claims to be GFM-compatible, but isn't, see e.g. https://github.com/kramdown/parser-gfm/issues/17 or https://github.com/barryclark/jekyll-now/issues/459#issuecomment-561336350.

**Comment by BenjaminRodenberg** [comment]
Thanks for looking into this @chlorenz! Then this seems to be an issue with kramdown and we have to wait until it is fixed there. I will close this issue and mark is as `wontfix`, because we cannot really do something.
