### ISSUE TITLE
Missing documentation for DUNE adapter

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#122]
The only resource we currently have is the README file of the adapter: https://github.com/precice/dune-adapter

**Comment by uekerman** [comment]
DUNE is currently still in the [third-party adapters list](https://precice.org/adapters-overview.html#third-party-adapters). For such we normally don't have specific documentation. Does not hurt though.
And there is Max's thesis, of course, to which we link.

**Comment by MakisH** [comment]
Ah, I did not see it in the list originally, thanks!
Then we don't really need anything for now.
