### ISSUE TITLE
Rename binprecice to precice-tools in docs

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#125]
Will be released with 2.4.0 and will take affect with 3.0.0

**Comment by davidscn** [comment]
We should change it in the documentation as early as possible for the same reasons as we renamed it already now, namely that people start using the upcoming features using `precice-tools`

**Comment by fsimonis** [comment]
We should probably sync that with the 2.4.0 release. Otherwise the documentation will be wrong by default as precice-tools currently doesn't exist.

**Comment by MakisH** [comment]
We can always update it now but write "until preCICE v2.3.0, this wall called binprecice".

**Comment by MakisH** [comment]
I think this has been solved already, I cannot find any instances of `binprecice` in the updated website.
