### ISSUE TITLE
"Edit me" on community stories leads to page template instead of testimonial

### ISSUE THREAD

**Issue by ajaust** [precice/precice.github.io#134]
If one wants to fix/edit a [community story](https://precice.org/community-projects.html) by clicking on the [edit me button](https://github.com/precice/precice.github.io_future/edit/master/pages/community/community-projects.md) one is forwarded to the page for editing `ROOT/pages/community/community-projects.md`. The file `community-projects.md` is only a page template which is filled with content from `ROOT/collections/_testimonials` so this is not helpful. 

It would be more user friendly if one would be able to directly edit a certain testimonial or to create a new testimonial. Would it possible to add such a feature?

**Comment by uekerman** [comment]
We realized a workaround in #137 for the moment:
- Removed the "edit me" button
- Extended the note with more info

@ajaust The solution you describe would be great. I am not sure how easy this would be though.

@chlorenz What do you think? If unnecessarily complicated, let's close.

**Comment by chlorenz** [comment]
What could be a solution? 
- Re-integrate the data into the page, which feels messy as it will be difficult to enforce a consistent format.
- A form, that takes the data and writes it to the collection.
- ...

While it's not ideal from a user perspective, I do like the workaround: The note with the additional information on the [community story page](https://precice.org/community-projects.html), is constructive, step by step, together with a concrete example for the pull request.

Another idea would be to add a fallback option in case a user is not able to do a pull request, e.g. to email somebody from the preCICE team. However, I assume the set of users who cannot do a pull request but can use preCICE is quite small.

All in all, while not ideal, my feeling is to not implement, for now.

**Comment by MakisH** [comment]
Simpler solution idea: we already know the name of the file we include. What if every story has a discrete, dedicated "edit me" button, that directly opens the corresponding file on GitHub? That could be styled as a hover-only element (similar to the "get URL" button we see in the headings). If too complicated, a simple text-only "Edit..." link at the bottom of each story would also do the job.

**Comment by MakisH** [comment]
Related to https://github.com/precice/precice.github.io/issues/283, which suggests an issue form template as an alternative solution.
