### ISSUE TITLE
Page on running Slurm job

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#144]
Common issues like
* networking
* hostfiles
* grouping executables
* checking failure states
* multiple mpirun calls

**Comment by MakisH** [comment]
We currently have the question of where such a page could fit.

We already had this problem with the [output files page](https://precice.org/fundamentals-output-files.html), currently listed under "Fundamentals", which now feels a bit like a "misc folder".

One way out would be to introduce a "Basic usage" / "First steps" / "Running" section, between "Installation" and "Configuration". This could include:
- A new short overview page, explaining the usual workflow, and linking to the "Configuration" and "Tooling" pages.
- [Output files](https://precice.org/fundamentals-output-files.html)
- This page on running on clusters

I guess two pages are already enough to justify a category, especially if this makes the structure more reasonable. We may find more to add in the future here.

**Comment by uekerman** [comment]
Upvote on the additional section, but we still need to find a good name. "Basic usage" and "First steps" do not fit in my opinion. It is neither what users should read first nor basic. Both potential pages (output files and running on clusters) are advanced things, right? "Running" might be too unspecific. We could actually call it "Misc" :see_no_evil: and move it behind "Couple your code"?

Anyway, we then also need to add a sentence here: https://precice.org/docs.html#where-to-find-what

**Comment by fsimonis** [comment]
What about a section called `Running codes` or `Running simulations`?
This fits nicely after the `Couple your code` section.

![image](https://user-images.githubusercontent.com/13552216/158181066-b392badf-3b9a-4eec-967d-3a60cc86fd4d.png) ![image](https://user-images.githubusercontent.com/13552216/158181156-285d8927-ee60-43b9-87ee-ad82e0d00881.png)
