### ISSUE TITLE
Add sections for special systems

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#15]
We still need to move the [old page on systems](https://github.com/precice/precice/wiki/Get-preCICE#special-systems) to the new website.
This can also be cleaned up a lot.

**Comment by uekerman** [comment]
> This can also be cleaned up a lot.

Sometimes legacy information can also be helpful. If somebody faces a similar cluster again. Certain things do not change. In my opinion, no need to over-engineer this here. A plain copy of the old content would already be good.

**Comment by fsimonis** [comment]
Added in 9b461ae
