### ISSUE TITLE
Add dependency and distro strategy to website

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#16]
Our dependencies follow a baseline (Ubuntu 18.04 LTS).
We need to formalize what our strategy for dependencies on distros is.

**Comment by MakisH** [comment]
On the content: My understanding is that we aim to support the latest two LTS releases (right now 18.04 and 20.04, as well as any actively supported newer version, e.g. 20.10 until June 2021).

This kind-of fits with our "breaking changes only every 2-3 years", as we can then remove the older of the two versions with every major preCICE release.

- preCICE 1.x (until 2020): Ubuntu 16.04, 18.04
- preCICE 2.x (2020-2022): Ubuntu 18.04, 20.04
- preCICE 3.x (2022-2024): Ubuntu 20.04 22.04

This means that we always need to support dependencies released 2-3 years ago, which is what we are currently doing. (Boost 1.65: August 2017, GCC 5.2: July 2015, ...)

**Comment by MakisH** [comment]
We already have the followin in the [system packages page](https://www.precice.org/installation-packages.html):

> We support the latest two Ubuntu LTS versions, as well as the latest normal Ubuntu release.

Closing for now, reopen if more is needed.
