### ISSUE TITLE
Consider switching to MathJax

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#170]
GitHub now supports rendering of LaTeX in Markdown using (MathJax)[https://github.blog/changelog/2022-05-19-render-mathematical-expressions-in-markdown/].

Switching the website to from KaTeX to MathJax may prevent incompatibilities between the two systems.

@chlorenz Are there any reasons to stick to KaTeX?

**Comment by chlorenz** [comment]
Yes, there are. My understanding is that MathJax was the first serious LaTeX engine, is widely in use, and has accessibility advantages. KaTeX on the other side is more modern, faster, and still being developed further. Here is an article [commenting on Github's MathJax introduction.](https://nschloe.github.io/2022/05/20/math-on-github.html)

Aside from that, both Github and [preCICE docs](https://precice.org/docs-meta-cheatsheet.html#latex-math-syntax) support the `$$ ... $$` notation. With LaTeX being LaTeX there should (in theory) be no incompatibilities.

**Comment by fsimonis** [comment]
Thanks for the info!
