### ISSUE TITLE
Links to the authors of many of the older testimonials/stories broken

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice.github.io#190]
I just realized that many of the links to the authors of the testimonials unter https://precice.org/community-projects.html are broken. This is normal, since people hand in their thesis or switch to another employer. Do you have a good solution in mind to update the links? Things I can imagine:

* Use a site from the very beginning where we can assume the personal site or account lasts longer (github, researchgate, linkedin not employer, university) - I imagine it is a bit strange to read "Jane doe, Institute for Made-Up Identities" and then arrive on github when clicking the link.
* Update as soon as we observe a link being outdated
* Get in contact with the author and ask her/him to update via PR

**Comment by uekerman** [comment]
I would suggest

> Update as soon as we observe a link being outdated

combined with a good portion of "ignore such problems".

**Comment by MakisH** [comment]
I fixed a few of these in #66.

Generally, we could also ask people to give us an ORCID URL, if they want. This should be permanent and they can update it however they want.
