### ISSUE TITLE
Website fails HTML validation

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#21]
Running the [HTML Validator on our website](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.precice.org%2F) reports a few issues. Many of them are very easy to fix (thus the good-first-issue), but some probably need some additional discussion, mainly:

![Screenshot from 2021-02-11 17-37-04](https://user-images.githubusercontent.com/4943683/107667425-da171100-6c8f-11eb-887f-983db45f93d4.png)
![Screenshot from 2021-02-11 17-37-23](https://user-images.githubusercontent.com/4943683/107667436-dc796b00-6c8f-11eb-9689-9902e5bf226f.png)

In case these two become show-stoppers, feel free to create individual issues.

**Comment by dcs-soni** [comment]
Hey. I would like to work on this issue.

**Comment by chlorenz** [comment]
Hi @dcs-soni, that would be great.

In case you are not familiar with jekyll, a good starting point are the [jekyll docs](https://jekyllrb.com/docs/), how to run jekyll locally, structure of the site etc. Then check the [preCICE docs overview page](https://www.precice.org/docs-meta-overview.html).

Looking at the errors, the second one should be easy to fix.

The first one comes from the `algolia.html` in `./_includes/`. The purpose is to style the search bar after it has been initialised by JS code, so pay attention to that.

If there is anything don't hesitate to ask @MakisH or myself.

**Comment by dcs-soni** [comment]
Hi @MakisH @chlorenz This is the first time I am using Ruby and getting involved in it. Tried to setup project locally but getting this error 👇 
![image](https://user-images.githubusercontent.com/52232900/110236148-39e49d00-7f5a-11eb-8c63-78df86ee6769.png)

**Comment by chlorenz** [comment]
Can you try without the `-l` flag, it doesn't work for me on Windows either?
Maybe also `--safe` might be the culprit.

**Comment by dcs-soni** [comment]
It worked without  ` -l ` flag in windows. Thanks! 

Can I create an issue regarding the installation steps for Windows, Mac ?

**Comment by chlorenz** [comment]
Not sure I understand - I don't think this issue relates to Mac OS?

**Comment by dcs-soni** [comment]
I've omitted the type attribute of the `style` element. After changing the errors what should I do now?  I mean I just have to create a branch and create a PR? or something else?

**Comment by dcs-soni** [comment]
> 
> 
> Not sure I understand - I don't think this issue relates to Mac OS?

I mean windows users and mac users have to follow different installation guides to run this project locally?

**Comment by chlorenz** [comment]
This issue is independent of this repo - it applies to all projects using jekyll. 
Yes, please create a branch and PR.
The warnings are less important, it's the errors that break the HTML validity.

**Comment by dcs-soni** [comment]
Need help - I've fixed the errors in `/_site/timeline/index.html` and checked again in HTML Validator, the errors are resolved now but the changes I've made in the files are not recognised by Git. After making changes I am getting "nothing to commit, working tree clean"

**Comment by chlorenz** [comment]
Hi, please check [jekyll docs - directory structure](https://jekyllrb.com/docs/structure/).

**Comment by dcs-soni** [comment]
Please check https://github.com/precice/precice.github.io/pull/27#issue-586730585

**Comment by chlorenz** [comment]
Hi @dcs-soni 
Your pull request removes the `type` attribute from the wrong tag.
As mentioned before please focus first on the errors. The warnings are not that important for now.
To test your changes please copy the source code into the HTML validator and post the result here.

**Comment by dcs-soni** [comment]
Okay. Thank you for your feedback. I am looking into this issue again.

**Comment by dcs-soni** [comment]
I am not able to locate the error in the project. Can you please guide me? I am not familiar with website build with jeykll and bit confused with the flow of pages.

**Comment by chlorenz** [comment]
I would recommend to start with the [jekyll step-by-step tutorial](https://jekyllrb.com/docs/step-by-step/01-setup/) to get a feel for  jekyll. The directory structure can look messy at first - it will be a lot clearer after you have done the tutorial. If you are new to jekyll it will take a couple of hours to a day to get up to speed. 

In a nutshell, when you do `jekyll serve/build` jekyll looks for all HTML and Markdown files, ignores folders that start with an underscore `_*/`, processes these files (parse front matter, resolve Liquid instructions, assemble files etc), and then places all files in `_site/`. The final end result is this static site.

**Comment by dcs-soni** [comment]
Thanks for the explanation. I am still learning how the jeykll works.. Will jump to the issue soon.
