### ISSUE TITLE
Update search engine Algolia in cron job

### ISSUE THREAD

**Issue by uekerman** [precice/precice.github.io#237]
Otherwise, we forget to update. Cron job could run every week (once per month might be too rarely, users are also searching for new things).

How to update: https://precice.org/docs-meta-search.html#updating-the-index

**Comment by MakisH** [comment]
We could automate this and provide the API key as a GitHub secret.

**Comment by chlorenz** [comment]
👍 

Currently we are on the free plan which includes 10000 'units' per month, of which we consume approximately 70%, at the moment. Which means we can't update the index more than once per month.
Algolia does have an [open source plan](https://www.algolia.com/for-open-source/) which would be perfect for us. Last time I contacted them, they weren't very responsive, we should definitely try again.

**Comment by MakisH** [comment]
I will open a new Algolia account on the name of preCICE and request the FOSS plan, in case the external contact was the reason for ghosting.

I will then create a workflow executed manually and on schedule (e.g., once per month).

It needs an API key, which I will share via the GitHub secrets.

**Comment by fsimonis** [comment]
We now have an open-source plan.

It may be possible to integrate the updates into the deployment pipeline of the website.
Alternative would be a cron job

**Comment by uekerman** [comment]
> It may be possible to integrate the updates into the deployment pipeline of the website.
Alternative would be a cron job

Could you please investigate? (not urgent)
