### ISSUE TITLE
Heading clicking moves the page (often unintentionally)

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#242]
User testing showed that some people have the habit to highlight and click text as they read. However, the clickable area around headings is very large, so clicking it results into unintentionally moving the whole page, which tends to be annoying.

I had not even observed that, as I always thought I could click on the chain icon that appears when hovering. Could we disable the clickability of the whole heading?

**Comment by fsimonis** [comment]
Good point. That happens to me quite often too.

I changed the behaviour to update the nav without jumping. So you can now click the header and then copy the link.

https://github.com/precice/precice.github.io/commit/9ef008850f83e73396d96237c93816fb40bfa784
