### ISSUE TITLE
ARPACK download links in Dependencies section of CalculiX adapter are outdated

### ISSUE THREAD

**Issue by IshaanDesai** [precice/precice.github.io#244]
The links in the commands

```bash
wget https://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz 
wget https://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz
```

which are in the section https://precice.org/adapter-calculix-get-calculix.html#building-arpack-from-source are outdated and need to be updated.

**Comment by MakisH** [comment]
Any clue what to change them to?

**Comment by IshaanDesai** [comment]
@Alphaoo1 you had found alternative links right? Can you please update them?

**Comment by prasadadhav** [comment]
@IshaanDesai Sorry for not getting back to you sooner. The alternate is now hosted [here](https://github.com/opencollab/arpack-ng). I have not been able to compile it on the HPC.
Although I am using a copy of the original ARPACK I got from @KyleDavisSA.
