### ISSUE TITLE
Information encoded in non-searchable image (e.g. installation on Windows or MacOS)

### ISSUE THREAD

**Issue by ajaust** [precice/precice.github.io#25]
Some information is available on the homepage, but not (easily) searchable/findable. An example is the information on installing preCICE on Windows. Information about using MinGW, the subsystem or so is only in the figure on https://www.precice.org/installation-overview.html 

When using the search engine to search for `windows`, most results point to `time-windows` or to MPI as dependency on Windows. For `macos` search results are also rather sparse and point to dependencies, but not to the installation. It would make sense to add this information also as text such that it is easier to find. Especially the installation on Windows or MacOS should be a section in the  written documentation.

This is partly triggered due to the following post on discourse: https://precice.discourse.group/t/precice-in-windows/500/2

**Comment by MakisH** [comment]
Good point, I can add this text. Unless you would like to! 😁

**Comment by ajaust** [comment]
I created a PR https://github.com/precice/precice.github.io/pull/26

One question that is open to me: Is this the only occasion of intormation hidden in a figure or does this happen at other places of the documentation as well?
