### ISSUE TITLE
Rendering of code diff broken / not supported?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice.github.io#260]
I just realized that the following is not rendered properly:

```diff cpp
+ addition
- removal
  all same
```

See https://precice.org/couple-your-code-porting-v2-3.html#add-relativereadtime-for-all-read-data-calls

**Comment by MakisH** [comment]
I did not even know of the option to provide a language next to the diff.

Even here, the language is just ignored:

```diff cpp
  #include <iostream>
  
- int main(void){
+ int main(){
    std::cout << "Hmmm...\n";
  }
```

Without the language, the diff works: https://precice.org/couple-your-code-porting-v1-2.html#single-step-setup

Where have you seen it working?

**Comment by BenjaminRodenberg** [comment]
Ok. If it works without the language then everything is fine. Thank you!
