### ISSUE TITLE
precice.github.io redirects to http://precice.org without TLS

### ISSUE THREAD

**Issue by cheriimoya** [precice/precice.github.io#274]
I don't really know how to change this, but maybe this is a good starting point: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

Also this is probably low prio.

**Comment by fsimonis** [comment]
Hi,
The DNS resolution happens before the connection is established aka independent of the accessed port and used protocol.

If you don't specify the protocol in your browser, then it's up to the browser to pick http or https. We have seen wildly different behaviours out in the wild. Some browsers even default to the `www.` subdomain, which makes everything even more confusing.

So, not a priority :wink:

**Comment by cheriimoya** [comment]
actually i just took some time to reproduce this issue: its not really depending on the browser.

whenever you create precice.github.io, the http -> https redirect will happen.

when you insert a custom domain in the page settings of the project, the checkbox for https will be removed

![image](https://github.com/precice/precice.github.io/assets/28303440/0eaa215e-04ac-4385-baa8-6e4ebe514c1d)

```
schoenbuch: ~ $ curl http://cheriimoya.de -I
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 17
Server: GitHub.com
Content-Type: text/html; charset=utf-8
...
```
 
and when i enable the https checkbox

```
schoenbuch: ~ $ curl http://cheriimoya.de -I
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 162
Server: GitHub.com
Content-Type: text/html
Location: https://cheriimoya.de/
...
```

so maybe you could double check under "settings > pages > custom domain > enforce https" since this is an issue that can be solved by github redirecting http -> https.
i am unsure why this is not the default tbh...

**Comment by uekerman** [comment]
I just ticked the box. Seems to work now.
