### ISSUE TITLE
Missing overview page of bindings

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#28]
In the [wiki](https://github.com/precice/precice/wiki/Non%E2%80%93standard-APIs) we have an overview page of all the bindings and how they are connected. At the same time, the bindings section in our documentation starts with a very short page on the [Fortran bindings](https://www.precice.org/installation-bindings-fortran.html).

We need to extend this. I plan to do this soon.

**Comment by uekerman** [comment]
The wiki information ended up here: https://www.precice.org/couple-your-code-api.html
The problem with the bindings documentation is whether things should go to "bulding" or to "couple your code".

**Comment by MakisH** [comment]
Thank you, I deleted the wiki page content and added a link. We still need an overview page then, even if only to redirect to that. And we may need even more changes here.

**Comment by MakisH** [comment]
We now have:

- A page section [Installing language bindings](https://precice.org/installation-overview.html)
- Pages for installing each language bindings (e.g., [Fortran](https://precice.org/installation-bindings-fortran.html)).
- An overview of all bindings in the page [Application programming interface](https://precice.org/couple-your-code-api.html).

So, I think we can close this issue now.
