### ISSUE TITLE
Unclear instructions in porting guide

### ISSUE THREAD

**Issue by carme-hp** [precice/precice.github.io#286]
In the **Porting from 2.x to 3.x**  guide the following points raised confusion: 
 
- About intialize:
> Remove initializeData() and initialize the data after defining the mesh and before calling initialize() if requiresInitialData() is true.

It think it would help to mention that `initializeData()` and `initialize()` have been merged into `initialize()`. I understand this means that the mesh and the data  (if needed) need to be specified before calling initialize()

- About  isActionRequired and markActionFullfiled:
>  Replace precice::constants::* with isActionRequired() and markActionFulfilled() with their respective requirement clause: requiresInitialData(), requiresReadingCheckpoint() or requiresWritingCheckpoint(). If these requirements are checked, then they are promised to be acted on.

Alternative: Replace isActionRequired() with their respective requirement clause: requiresInitialData(), requiresReadingCheckpoint() or requiresWritingCheckpoint(). If these requirements are checked, then they are promised to be acted on, so markActionFulfilled is not needed anymore.

**Comment by carme-hp** [comment]
Another unclear point:

> Change integer input argument data ID to string arguments mesh name and data name in the API commands hasData, writeBlockVectorData, writeVectorData, writeBlockScalarData, writeScalarData, readBlockVectorData, readVectorData, readBlockScalarData, readScalarData, requiresGradientDataFor, writeBlockVectorGradientData, writeVectorGradientData, writeBlockScalarGradientData, writeScalarGradientData

Since all of this functions have now been simplified to `readData`, `writeData`and `writeGradientData` it would be nice to mention that as an additional point after the previous one.

**Comment by MakisH** [comment]
Closed by #287.
