### ISSUE TITLE
Fix open `TODO`s from https://github.com/precice/precice.github.io/pull/299

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice.github.io#301]
There are some TODOs I identified in https://github.com/precice/precice.github.io/pull/299 while updating the API to v3. The following sections are outdated:

* Step 8 – Mesh connectivity
* Direct access to received meshes

Please refer to the diff of the PR for details.

**Comment by MakisH** [comment]
I assume this has already been resolved elsewhere, right?

**Comment by uekerman** [comment]
yes, all done
