### ISSUE TITLE
Explain time drift between preCICE and Solver

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#303]
The time of preCICE and the Solver can drift apart due to how we handle time in coupling schemes.

In short, if a solver does a time step of $$\delta t = nextMaxTimeStepSize() - \gamma, \gamma < \epsilon$$, then preCICE rounds time to the end of the time window.
This means that $\gamma$ is the difference between preCICE and solver time, which adds up in case of a large amount of time windows (not time steps).

Once $\sum\gamma > \epsilon$, then this drift is affecting numerical comparisons in preCICE, which leads to pink elephants in solvers.

Problem: https://github.com/precice/precice/issues/1866
Error check: https://github.com/precice/precice/pull/1867

**Comment by MakisH** [comment]
@BenjaminRodenberg @fsimonis  @uekerman  This is something we can already document and merge, right?

**Comment by fsimonis** [comment]
Solved by #326
