### ISSUE TITLE
Possible search alternative

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#336]
I stumbled across the documentation of mdbook, the tool Rust uses to generate documentation.
Their search looks decent and works offline, if we ever run into issues with Algolia search, we may be able to use their search instead.

Documentation: https://rust-lang.github.io/mdBook/index.html
Searcher implementation in JS: https://github.com/rust-lang/mdBook/tree/master/src/theme/searcher
Indexer implementation in Rust: https://github.com/rust-lang/mdBook/blob/master/src/renderer/html_handlebars/search.rs
Example search index: https://rust-lang.github.io/mdBook/searchindex.js

**Comment by uekerman** [comment]
Let's close if we get the open-source plan from Algolia.

**Comment by fsimonis** [comment]
We got an open-source plan. Closing
