### ISSUE TITLE
Ghost image file in the repository

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#373]
We currently have a stray/ghost file in the repository, which I don't know why it ended up here, but it is rather annoyingly appearing in all of `git status`, even after adding it to a `.gitignore`:

```shell
~/repos/precice/website/images [ghost-image]$ gits
On branch ghost-image
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   .gitignore

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../imported/tutorials (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	docs-tooling-fmi-runner-setup.png
```

`rm` and `git rm` seem to be ineffective.

@fsimonis I think you worked a bit on some image cleanups at some point, any clue where this comes from?

**Comment by fsimonis** [comment]
Fixed via a7c567a84fe7e8107ba21d864d4213104d9693ed
