### ISSUE TITLE
"Basic Tutorials" confuse the sidebar

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#376]
Opening a basic tutorial highlights it both in the "Basic Tutorials" and the "All Tutorials"

![image](https://github.com/precice/precice.github.io/assets/13552216/28f8ab64-7435-4805-b767-6c2203d9b062)

**Comment by uekerman** [comment]
wasn't this done on purpose in #372?

**Comment by MakisH** [comment]
It is not exactly on purpose, it is just a "feature" of how the relation of pages to sidebars is implemented, which assume that each page only appear once in the sidebar.

The difference now is that we list all tutorials (in groups), which is I think more important than the duplication issue.

What we can still do, is remove the "Basic cases" collection from the sidebar and let people discover those through the overview, or a dedicated page in the sidebar. But I think this is not a trivial discussion.

**Comment by fsimonis** [comment]
Technically, we could add a "link-only" key to the "basic" entries skip marking those links as active items

**Comment by MakisH** [comment]
I would need to tinker a bit to understand how this works. If you already know, please go ahead.

**Comment by fsimonis** [comment]
Solved by #377
