### ISSUE TITLE
Add rust bindings in overview

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice.github.io#416]
Add rust bindings to our [overview](https://github.com/precice/precice.github.io/tree/master/material/overview) since we have [rust bindings](https://github.com/precice/rust-bindings) and I'm already hearing the 3rd talk about Rust at PDESoft today :smirk:

**Comment by BenjaminRodenberg** [comment]
I'm right now clueless how I can update the picture. I tried using inkscape but was not sure about the font + fontsize we use here. Any documentation hints?

**Comment by MakisH** [comment]
The image you found is published on the website, and we generally want(ed) people to use it as-is.
The sources are on Nextcloud, where you can also find related documentation and the font used (CMU Bright), as well as a few other related sources and variants of this picture.
