### ISSUE TITLE
Integrate Google Scholar publications

### ISSUE THREAD

**Issue by chlorenz** [precice/precice.github.io#45]
Add a link on the landing page that points to all publications citing preCICE. If possible display the total number of publications.

**Comment by uekerman** [comment]
"Cited 126 times on Google Scholar" and link to this page: https://scholar.google.com/scholar?hl=en&as_sdt=2005&sciodt=0,5&cites=5053469347483527186&scipsc=&q=&scisbd=1

**Comment by chlorenz** [comment]
I've done some research on the how to get the number of citations from Google Scholar. Unfortunately Google does not provide an API for Scholar. I see three main workarounds:

 a) Query and parse the HTML (or use a library to do that), which is inefficient and slow, so it would have to be done at build time rather than in real time. See e.g. [scholarly.py](https://github.com/scholarly-python-package/scholarly).
 b) Use a third-party API, but this comes at extra cost. See e.g. [SERP API](https://serpapi.com/google-scholar-api).
 c) Manually export Google Scholar citations from time to time to BibTeX (or manually curate a .bib for that matter) and then use [jekyll-scholar](https://github.com/inukshuk/jekyll-scholar) to parse and display the bibliography.

Further information:
 * https://academia.stackexchange.com/questions/142063/export-google-scholar-search-for-fine-grained-analysis
 * https://academia.stackexchange.com/questions/34970/how-to-get-permission-from-google-to-use-google-scholar-data-if-needed
 * https://academia.stackexchange.com/questions/24493/how-can-i-export-my-google-scholar-library-as-a-bibtex-format/147115#147115

**Comment by chlorenz** [comment]
In the end I found a relatively easy solution following approach a) based on a custom Jekyll plugin from [Jonathan Chang](https://jonathanchang.org/blog/easily-showcase-your-google-scholar-metrics-in-jekyll).

@uekerman Ideas where we should display the number of citations? Currently in the literature section on the landing page.

**Comment by uekerman** [comment]
> @uekerman Ideas where we should display the number of citations? Currently in the literature section on the landing page.

That's exactly what I would have suggested
