### ISSUE TITLE
Check the file size of tutorial images

### ISSUE THREAD

**Issue by chlorenz** [precice/precice.github.io#48]
- [x] Check file size of existing images @MakisH 
- [x] Write a Github action to monitor newly added images @DavidSCN

**Comment by davidscn** [comment]
Actually I forgot the important question: which size should be the threshold? Which size is still admissible and which not?

**Comment by chlorenz** [comment]
I would suggest to warn above 250 KB - but that arbitrary and open to discussion.

**Comment by MakisH** [comment]
I resized almost every static image above 250 KB. I also reduced the GIF size significantly (removing frames or compressing).

**Comment by davidscn** [comment]
Has been added in precice/tutorials#203. We have no an image limit of 250kb and a gif limit (only a single one apparent) 2.2.mb.

**Comment by uekerman** [comment]
I guess we can close this one.
