### ISSUE TITLE
Dead links in "Communication configuration" page

### ISSUE THREAD

**Issue by ajaust** [precice/precice.github.io#62]
The "communication configuration" page is incomplete. The link with further information if you are having problems with establishing the communication does not work. It links to `TODO` which gives a "404 page not found" error.

The problem is in this file https://github.com/precice/precice.github.io/blob/master/pages/docs/configuration/configuration-communication.md in line 32. The critical section is the one below:

```text
{% include important.html content="If you face any problems with establishing the communication, have a look [here](TODO)." %}
```

It is not clear to me if the page it should link to is actually missing or if the link just needs an update.

**Comment by MakisH** [comment]
I think the "TODO" here means essentially porting this wiki page to the new documentation: https://github.com/precice/precice/wiki/Problems-with-Establishing-the-Communication

I guess this is something we forgot at some point. (right, @uekerman?)

Thank you for reporting, I am going through this now and adding a GitHub Action to check the non-TODO links.

**Comment by uekerman** [comment]
> I guess this is something we forgot at some point. (right, @uekerman?)

IIRC we wanted to make this an FAQ post in the forum.

**Comment by ajaust** [comment]
I want to add the the link  `[special case](macOS)` in line 18 does not work either for me.

Edit: Nor does the link `([for OpenMPI, for example](TODO))` in line 26.

Edit 2: Is their any link on this page that does work? There are quite some `TODO` link on this page.

Edit 3: I just saw that #66 seems to fix this issue.

**Comment by uekerman** [comment]
And @MakisH added https://precice.discourse.group/t/help-the-participants-are-not-finding-each-other/646/4
