### ISSUE TITLE
Include parts of pages from different repositories

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#8]
In some cases, we want to manage the documentation files together with the respective code files. This particularly affects:
- installation & configuration of adapters: we want to remember that we need to update the documentation and not have to maintain multiple PRs across repositories. This makes reviewing and version management easier.
- tutorials: we want each tutorial case to have the instructions together with the code. This makes reviewing easier and upgrades the [tutorials](https://github.com/precice/tutorials) repository to a place for "full tutorials", instead of cases that need more description to run. It also helps reduce duplication, as we currently also maintain README files for each tutorial.
- the XML reference. We already create the XML reference page by including a static asset `xmlreference.md`:

https://github.com/precice/precice.github.io_future/blob/2250cc924faaa58ce476e32494df67472234c169/pages/docs/configuration/configuration-xml-reference.md#L15

This file is currently hosted in [_include/](https://github.com/precice/precice.github.io_future/blob/master/_includes/xmlreference.md). Could we actually store it in the [precice](https://github.com/precice/precice) repository and get it at build time?

If yes, **should we maintain the documentation files for each repository separately (e.g. in a `docs/` directory) and collect all the parts when building the documentation?**

A side-effect would be that we need to trigger a rebuild every time we update the `master` of a repository, but this is something we anyway need already.

Implementation ideas that popped up include [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) or a GitHub Action that copies the files.

**Comment by chlorenz** [comment]
@MakisH Checking whether this issue is still open?

**Comment by MakisH** [comment]
From the technical side, we can close it. We can then discuss today or (better) in the next months if this is an approach we want to follow for more components.
