### ISSUE TITLE
Missing instructions on how to install FEniCS

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io#82]
In the [FEniCS adapter documentation](https://precice.org/adapter-fenics.html), we currently have instructions on how to install the adapter.

In other adapter, for example for [OpenFOAM](https://precice.org/adapter-openfoam-support.html) and for [CalculiX](https://precice.org/adapter-calculix-get-calculix.html), we also have some instructions on how to install the solver itself first. It would be useful to have some short instructions here as well with the preferred or most common way to install FEniCS (as well as which version and any other questions that the user may have).

One would argue "it is not our job to document the solvers", but it is actually to our strong favor. New users often know/have one of the solvers, but they know nothing about the rest of the solvers they need to run tutorials. Even further, many of our users are students that do not have much experience with simulation software and installing software on Linux anyway. Giving some first guidance definitely helps users start with preCICE.

@IshaanDesai @BenjaminRodenberg would you maybe like to add something here? I could also prepare something, but you are probable the right people for that.

**Comment by IshaanDesai** [comment]
@MakisH thanks for bringing this up. It is indeed important to provide basic information regarding FEniCS installation and this is evident from the fact that we have had multiple users asking us about FEniCS installation before getting on to use the adapter. I will add a section :+1:
